name: eodc-examples
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - xarray
  - pandas
  - matplotlib
  - affine
  - pystac
  - pystac-client
  - odc-stac
  - odc-geo
  - rich
  - ipywidgets
  - pip:
      #- "eodc==2025.10.2"
      - eodc-connect
      - contextily
      - openeo
